#!/bin/bash

# vem's main code

# Check for updates
[ ! -d ~/.vem ] && $(find $HOME -type d -name vem)/install
if [[ `diff $(find $HOME -type d -name vem)/.vem ~/.vem` ]]; then echo "Updating vem..."; $(find $HOME -type d -name vem)/install; fi

# Load lib
source $HOME/.vem/.lib

__vem() {
  # Parse args
  [ "$1" == "" ] && ( cat $HOME/.vem/.help | head -1; exit ) || __args $@
}

__vem $@

# Cleanup for accidental sourcing
unset __vem __args __cwd __cwvem __setve __repo __del __delve arg
