#!/bin/bash

# Virtual Environment Manager for Python and Node
# Funcs and vars
__vem() {
  # Check special args
  [[ "$@" == "" ]] && ( cat $HOME/.vem/.help | head -1; exit )
  [[ ${1%*-} == 'h' || ${1%*-} == 'help' ]] && ( cat $HOME/.vem/.help; exit )
  [[ ${1%*-} == 'v' || ${1%*-} == 'version' ]] && ( cat $HOME/.vem/.version; exit )

  # Parse vem location
  local __cwd=`pwd`
  local vemPath=`[[ ${1%-} =~ 'p' ]] && echo "$HOME/.vem/py" || echo "$HOME/.vem/js"`
}

# Main
# Ensure setup of VEM
[ ! -d $HOME/.vem ] && mkdir $HOME/.vem && mkdir $HOME/.vem/py && mkdir $HOME/.vem/js
[ ! -e $HOME/.vem/.help ] && cp "$(find ~ -type d -name VEM)/.help" $HOME/.vem
[ ! -e $HOME/.vem/.version ] && cp $(find ~ -type d -name VEM)/.version $HOME/.vem

# Call VEM
__vem $@

# Cleanup under accidental sourcing
unset __vem
